### ISSUE TITLE
Admin Merchant Create

### ISSUE THREAD

**Issue by redferret** [redferret/little-esty-shop#12]
As an admin,
When I visit the admin merchants index
I see a link to create a new merchant.
When I click on the link,
I am taken to a form that allows me to add merchant information.
When I fill out the form I click ‘Submit’
Then I am taken back to the admin merchants index page
And I see the merchant I just created displayed
And I see my merchant was created with a default status of disabled.

**Comment by JoannaCoPo** [comment]
Hey all - I might just be sleep deprived but can someone double check for me:
Has this story already been addressed in the code? In the admin/merchants/index.html.erb (on our main branch) on line 4 we have:
`<%= link_to 'Add New Merchant', new_admin_merchant_path, class:'btn btn-primary btn-sm'%>`.
Is this any different from what this sotry is asking (is looks really similar to how I would approach it)? I'm also not sure I'm seeing a test for this. Thank you!  @redferret @ahenzler @JoePeterson51 @denverdevelopments
